### ISSUE TITLE
Support Refresh Metadata on folders

### ISSUE THREAD

**Issue by ctinghino** [celador/ForceCode#124]
Actually, it is possible to refresh a single file, the project from the package.xml or all files from server. No option is available to refresh a single metadata type, for example: "Refresh all classes".
This feature is important on big projects, when a refresh of all the project is critical.

It would be great to add the option on the metadata folder:
Eg: on the src/classes folder, the refresh command refreshes all the classes.

**Comment by celador** [comment]
I agree.  It would be a great feature.  

Can you take a shot at looking into implementing it yourself?  There are directions at the bottom of the Readme that should help you getting started.

**Comment by ctinghino** [comment]
I cloned the project, executed: 
```
> npm install
> npm install typescript -g
```
But when I try to debug the extension (F5), I receive this error:

```
C:\Program Files\Microsoft VS Code\Code.exe --debugBrkPluginHost=21440 --debugId=9a592664-93a7-476f-b1f4-b94ec4b764dc --extensionDevelopmentPath=c:\Users\Christian\ForceCode 
Activating extension `JohnAaronNelson.ForceCode` failed: Cannot find module 'c:\Users\Christian\ForceCode\out\src\extension'.
Activating extension `JohnAaronNelson.ForceCode` failed:  Cannot find module 'c:\Users\Christian\ForceCode\out\src\extension'
Here is the error stack:  Error: Cannot find module 'c:\Users\Christian\ForceCode\out\src\extension'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.z.J.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:401761)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Function.d [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:27881)
	at m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:416873)
	at e._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:422115)
	at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:421591)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:419783)
```

**Comment by ctinghino** [comment]
The problem is in the package.json file, the `compile` script needs to be changed from:
```
"compile": "./node_modules/typescript/bin/tsc -watch -p ./",
```
to:
```
"compile": "node ./node_modules/typescript/bin/tsc -watch -p ./",
```
