### ISSUE TITLE
"Retrieve Package/Metadata -> Get All Files from org" never finishes

### ISSUE THREAD

**Issue by doug-episource** [celador/ForceCode#217]
From the ForceCode menu, selecting "Retrieve Package/Metadata" => "Get All Files from org" never finishes and does not show any errors. Retrieving other options, such as "Get All Apex Classes from org" completes as expected. This has worked in previous versions, but I do not remember which version.

**To Reproduce**
1. Go to ForceCode Menu
2. Click on Retrieve Package/Metadata
3. Click on Get All Files from org
4. Wait

**Expected behavior**
All files from the Org should be downloaded. If there is an error, the error should be reported. No files are downloaded, no progress is evident.

**Desktop (please complete the following information):**
 - OS: macOs, Sierra, 10.12.16
 - VS Code v 1.29.1
 - ForceCode v3.11.1

**Comment by daishi4u** [comment]
Can you try again with 3.11.2?

**Comment by doug-episource** [comment]
I have tried with 3.11.2 and the same result. Nothing downloads -- no errors, no output in the window for extensions. I have also tried on a Windows 10 box, same thing. It still downloads individual Metadata types, such as Apex Classes, but I have not tried all to see where the failure happens.

**Comment by daishi4u** [comment]
@doug-episource try to download just static resources and let me know if that succeeds or not. If it doesn't then go to the option where you can select types and select all except static resources and let me know if that works. If that succeeds then could you go through the static resources in the org and tell me all of the compressed/zipped types?

**Comment by doug-episource** [comment]
So, that did work, just the Static Resources. I am attaching an image with all the types... Let me know what other info you need.

![screen shot 2018-12-12 at 4 54 06 pm](https://user-images.githubusercontent.com/28274799/49908281-a67d9980-fe2e-11e8-8704-7d8d93c2eba7.png)

**Comment by daishi4u** [comment]
@doug-episource can you try out this beta build: https://drive.google.com/file/d/1jO_kbjZl7MXQBnpum1XZf6Ut1ewUl3uW/view?usp=sharing

The only difference between this and 3.11.2 is that it has better error handling for failing retrieve operations, so I'm hoping it will reveal the root cause and you can report any error that it gives you. Then I can fix it for the next release :)

**Comment by doug-episource** [comment]
I have been running the retrieve for about 30 minutes and nothing has come down. There are also no errors or progress information in the Output for ForceCode. Should I be looking there? Or should I look elsewhere?

**Comment by doug-episource** [comment]
I decided to grab the dev-next branch and debug that. Here is the output on the retrieve:
```
/Applications/Visual Studio Code.app/Contents/MacOS/Electron --debugBrkPluginHost=7598 --debugId=4da01d61-e82d-42d6-bf12-addcafcff575 --extensionDevelopmentPath=/Users/dougthompson/Documents/Dev/ForceCode 
vscode-icons is active!
Starting connection service...
Starting Code Coverage Service...
Cannot find en-us, defaulting to en
Cannot find en-us, defaulting to en
vscode-icons is active!
Initializing ForceCode service
Starting ForceCode service
SFDX CLI Extension Activated
Setting up ISV Debugger environment variables
Configured file watcher for .sfdx/sfdx-config.json
[CoenraadS.bracket-pair-colorizer] Accessing a window scoped configuration for a resource is not expected. To associate 'bracketPairColorizer.excludedLanguages' to a resource, define its scope to 'resource' in configuration contributions in 'package.json'.
[CoenraadS.bracket-pair-colorizer] Accessing a window scoped configuration for a resource is not expected. To associate 'bracketPairColorizer.excludedLanguages' to a resource, define its scope to 'resource' in configuration contributions in 'package.json'.
[CoenraadS.bracket-pair-colorizer] Accessing a window scoped configuration for a resource is not expected. To associate 'bracketPairColorizer.excludedLanguages' to a resource, define its scope to 'resource' in configuration contributions in 'package.json'.
{"status":0,"result":{"nonScratchOrgs":[{"orgId":"00Di0000000HQ7fEAG","accessToken":"e4bc633c111674ab372607c1c174fd89241985feb9fd1a913f8feff65bfa8d8f4fc50476a8bfddd91eec819095171ba963245a281316e57caa61332c9ba9e6e03d68066a38d0842f69faaa339df9a3edc772de719dc52961c719baa99eadb0c25e1ab2cbeb595065549fefe72816310cd0512ef369e9:2cdbbaf52d1742c5448b9f70da390eaa","instanceUrl":"https://na49.salesforce.com","loginUrl":"https://login.salesforce.com","username":"doug.thompson@episource.com","connectedStatus":"Connected","lastUsed":"2018-12-13T17:28:03.000Z"},{"orgId":"00D0q0000008otrEAA","accessToken":"2d51819d63852bcb8bad598b185afd422024d1d901bf6f458a13ea4cf32e81d2009e07ad30df5521e568bc0c7da14575852ae413481e5ad414d8353a42cdef58e50216eb7c0edfed4bd6f91f8d0ed9b1aa50d7e48d78a3d5b344ad78426976ddd12417902e6f0d4968e2dad21af0ad6a0242a9cebcae:a5531b685ec93059fb6977c4d35242f2","instanceUrl":"https://cs64.salesforce.com","loginUrl":"https://test.salesforce.com","username":"doug.thompson@episource.com.epiuat","connectedStatus":"invalid_grant","lastUsed":"2018-12-13T17:27:39.000Z"},{"orgId":"00D1h0000000TtJEAU","accessToken":"05bb3c9cc969a17a2652907d40c0728a556a1761945dbf7bec7edce18a0da459623ee6d564b475769ae660ed0162ca60e359d57822a5745be80f57a088e55a6b9793df298dfff710e38969d0d8506951cfccdcdc1f98047b352a545f4403db9daee75d8bf1742e5a88d44d565a4f510e028315fb8e4f:bc03ac804d4d6b2828b2e60f2fff027d","instanceUrl":"https://cs79.salesforce.com","loginUrl":"https://test.salesforce.com","username":"doug.thompson@episource.com.runtests","connectedStatus":"invalid_grant","lastUsed":"2018-12-13T17:27:39.000Z"}],"scratchOrgs":[]}}
Orgs refreshed
{"status":0,"result":{"username":"doug.thompson@episource.com","id":"00Di0000000HQ7fEAG","connectedStatus":"Connected","accessToken":"00Di0000000HQ7f!ARUAQH7YALkQUXmFhSalvFmgI1WnrIPZCIumMhdM5ZzRAV.lfbzZDKAUljc6jYQaiUNSIktZDV4QyxAJBbYTeKdvrtx7Bxmp","instanceUrl":"https://na49.salesforce.com","clientId":"SalesforceDevelopmentExperience"}}
{"status":0,"result":{"nonScratchOrgs":[{"orgId":"00Di0000000HQ7fEAG","accessToken":"e4bc633c111674ab372607c1c174fd89241985feb9fd1a913f8feff65bfa8d8f4fc50476a8bfddd91eec819095171ba963245a281316e57caa61332c9ba9e6e03d68066a38d0842f69faaa339df9a3edc772de719dc52961c719baa99eadb0c25e1ab2cbeb595065549fefe72816310cd0512ef369e9:2cdbbaf52d1742c5448b9f70da390eaa","instanceUrl":"https://na49.salesforce.com","loginUrl":"https://login.salesforce.com","username":"doug.thompson@episource.com","connectedStatus":"Connected","lastUsed":"2018-12-13T17:48:58.000Z"},{"orgId":"00D0q0000008otrEAA","accessToken":"2d51819d63852bcb8bad598b185afd422024d1d901bf6f458a13ea4cf32e81d2009e07ad30df5521e568bc0c7da14575852ae413481e5ad414d8353a42cdef58e50216eb7c0edfed4bd6f91f8d0ed9b1aa50d7e48d78a3d5b344ad78426976ddd12417902e6f0d4968e2dad21af0ad6a0242a9cebcae:a5531b685ec93059fb6977c4d35242f2","instanceUrl":"https://cs64.salesforce.com","loginUrl":"https://test.salesforce.com","username":"doug.thompson@episource.com.epiuat","connectedStatus":"invalid_grant","lastUsed":"2018-12-13T17:48:58.000Z"},{"orgId":"00D1h0000000TtJEAU","accessToken":"05bb3c9cc969a17a2652907d40c0728a556a1761945dbf7bec7edce18a0da459623ee6d564b475769ae660ed0162ca60e359d57822a5745be80f57a088e55a6b9793df298dfff710e38969d0d8506951cfccdcdc1f98047b352a545f4403db9daee75d8bf1742e5a88d44d565a4f510e028315fb8e4f:bc03ac804d4d6b2828b2e60f2fff027d","instanceUrl":"https://cs79.salesforce.com","loginUrl":"https://test.salesforce.com","username":"doug.thompson@episource.com.runtests","connectedStatus":"invalid_grant","lastUsed":"2018-12-13T17:48:58.000Z"}],"scratchOrgs":[]}}
Orgs refreshed
Project is not for ISV Debugger
Deleted environment variables SFDX_DEFAULTUSERNAME and SFDX_INSTANCE_URL
Cannot find en-us, defaulting to en
Cannot find en-us, defaulting to en
SFDX SLDS Linter Extension Activated
Cannot find en-us, defaulting to en
Cannot find en-us, defaulting to en
Apex Debugger Extension Activated
Apex Replay Debugger Extension Activated
in activate, added breakpointsSub to subscriptions, activation complete
rejected promise not handled within 1 second
{"status":0,"result":["APXTConga4__Conga_Template__Feed","AcceptedEventRelation","Account","AccountContactRole","AccountFeed","AccountHistory","AccountPartner","AccountShare","ActionLinkGroupTemplate","ActionLinkTemplate","ActivityHistory","AdditionalNumber","Address","AggregateResult","Announcement","ApexClass","ApexComponent","ApexEmailNotification","ApexLog","ApexPage","ApexPageInfo","ApexTestQueueItem","ApexTestResult","ApexTestResultLimits","ApexTestRunResult","ApexTestSuite","ApexTrigger","AppDefinition","AppExtension","AppMenuItem","AppTabMember","Approval","Asset","AssetFeed","AssetHistory","AssetRelationship","AssetRelationshipFeed","AssetRelationshipHistory","AssetTokenEvent","AssignedResource","AssignedResourceFeed","AssignmentRule","AssociatedLocation","AssociatedLocationHistory","AsyncApexJob","AttachedContentDocument","Attachment","AuraDefinition","AuraDefinitionBundle","AuraDefinitionBundleInfo","AuraDefinitionInfo","AuthConfig","AuthConfigProviders","AuthProvider","AuthSession","BackgroundOperation","BackgroundOperationResult","BatchApexErrorEvent","BrandTemplate","BrandingSet","BrandingSetProperty","BusinessHours","BusinessProcess","CKSW_BASE__Demand__Share","CKSW_BASE__Employee_Absence__Share","CKSW_BASE__Location__History","CKSW_BASE__Location__Share","CKSW_BASE__Request__Feed","CKSW_BASE__Request__History","CKSW_BASE__Request__Share","CKSW_BASE__Resource__Feed","CKSW_BASE__Resource__History","CKSW_BASE__Resource__Share","CKSW_BASE__Service__Feed","CKSW_BASE__Service__History","CKSW_BASE__Service__Share","CKSW_BASE__Shift_Type_Break__History","CKSW_BASE__Shift__Feed","CKSW_BASE__Shift__History","CKSW_BASE__Shift__Share","CKSW_BASE__Swap_Request__Feed","CKSW_BASE__Team__Feed","CKSW_BASE__Timesheet__Feed","CKSW_BASE__Timesheet__Share","CT_Member__History","CallCenter","Campaign","CampaignChangeEvent","CampaignFeed","CampaignHistory","CampaignMember","CampaignMemberStatus","CampaignShare","Case","CaseComment","CaseContactRole","CaseFeed","CaseHistory","CaseShare","CaseSolution","CaseStatus","CaseSubjectParticle","CaseTeamMember","CaseTeamRole","CaseTeamTemplate","CaseTeamTemplateMember","CaseTeamTemplateRecord","CategoryData","CategoryNode","Chart__History","ChatterActivity","ChatterExtension","ChatterExtensionConfig","Check_In_Out__History","ClientBrowser","Client__History","Client__Share","CollaborationGroup","CollaborationGroupFeed","CollaborationGroupMember","CollaborationGroupMemberRequest","CollaborationGroupRecord","CollaborationInvitation","ColorDefinition","CombinedAttachment","Community","Companies__History","ConnectedApplication","Contact","ContactFeed","ContactHistory","ContactShare","ContentAsset","ContentBody","ContentDistribution","ContentDistributionView","ContentDocument","ContentDocumentFeed","ContentDocumentHistory","ContentDocumentLink","ContentDocumentSubscription","ContentFolder","ContentFolderItem","ContentFolderLink","ContentFolderMember","ContentNotification","ContentTagSubscription","ContentUserSubscription","ContentVersion","ContentVersionComment","ContentVersionHistory","ContentVersionRating","ContentWorkspace","ContentWorkspaceDoc","ContentWorkspaceMember","ContentWorkspacePermission","ContentWorkspaceSubscription","Contract","ContractContactRole","ContractFeed","ContractHistory","ContractStatus","CorsWhitelistEntry","CronJobDetail","CronTrigger","CspTrustedSite","CustomBrand","CustomBrandAsset","CustomHttpHeader","CustomObjectUserLicenseMetrics","CustomPermission","CustomPermissionDependency","Dashboard","DashboardComponent","DashboardComponentFeed","DashboardFeed","DataAssessmentFieldMetric","DataAssessmentMetric","DataAssessmentValueMetric","DataIntegrationRecordPurchasePermission","DataStatistics","DataType","Data__Feed","DatacloudAddress","DatasetExport","DatasetExportEvent","DatasetExportPart","DeclinedEventRelation","DigitalSignature","Document","DocumentAttachmentMap","Domain","DomainSite","DuplicateRecordItem","DuplicateRecordSet","DuplicateRule","EmailCapture","EmailDomainKey","EmailMessage","EmailMessageRelation","EmailServicesAddress","EmailServicesFunction","EmailTemplate","EmbeddedServiceDetail","EmbeddedServiceLabel","EntityDefinition","EntityParticle","EntitySubscription","EnvironmentHub","EnvironmentHubInvitation","EnvironmentHubMember","EnvironmentHubMemberRel","EpiSales__History","EpiSales__Share","Event","EventBusSubscriber","EventFeed","EventLogFile","EventRecurrenceException","EventRelation","EventWhoRelation","ExternalDataSource","ExternalDataUserAuth","ExternalSocialAccount","FedEx_Request__Feed","FedEx_Request__History","FeedAttachment","FeedComment","FeedItem","FeedLike","FeedPollChoice","FeedPollVote","FeedRevision","FeedSignal","FeedTrackedChange","FieldDefinition","FieldHistoryArchive","FieldPermissions","FieldServiceMobileSettings","FileSearchActivity","FiscalYearSettings","FlexQueueItem","FlowInterview","FlowInterviewShare","FlowRecordRelation","FlowStageRelation","Folder","FolderedContentDocument","ForecastShare","ForecastingShare","GrantedByLicense","Group","GroupMember","HHA2_Members__History","HHA_Client__History","HHA_Members__History","HHA_Project__History","HHA_Provider__History","Holiday","IconDefinition","Idea","IdeaComment","IdpEventLog","InstalledMobileApp","KnowledgeableUser","Lead","LeadFeed","LeadHistory","LeadShare","LeadStatus","LightningComponentBundle","LightningComponentResource","LightningComponentTag","LightningExitByPageMetrics","LightningExperienceTheme","LightningToggleMetrics","LightningUsageByAppTypeMetrics","LightningUsageByBrowserMetrics","LightningUsageByFlexiPageMetrics","LightningUsageByPageMetrics","ListEmail","ListEmailIndividualRecipient","ListEmailRecipientSource","ListEmailShare","ListView","ListViewChart","ListViewChartInstance","Location","Location2__Feed","Location2__History","LocationFeed","LocationHistory","LocationShare","Location_Invoice__Feed","LoginGeo","LoginHistory","LoginIp","LookedUpFromActivity","MC_Hcc_Category__History","MRT_Appointment__History","MRT_Performance__History","MRT_Performance__Share","MRT__History","Macro","MacroHistory","MacroInstruction","MacroShare","MailmergeTemplate","Mailroom_Activity__Feed","Mailroom_Activity__History","MaintenanceAsset","MaintenanceAssetFeed","MaintenanceAssetHistory","MaintenancePlan","MaintenancePlanFeed","MaintenancePlanHistory","MaintenancePlanShare","MatchingRule","MatchingRuleItem","Medical_Group__History","Medical_Record_Code__History","Member_Medical_Record__History","MobileSettingsAssignment","Name","NamedCredential","Note","NoteAndAttachment","OC_Coaching__History","OC_Coaching__Share","OauthToken","ObjectPermissions","OnboardingMetrics","OpenActivity","OperatingHours","OperatingHoursFeed","Opportunity","OpportunityCompetitor","OpportunityContactRole","OpportunityFeed","OpportunityFieldHistory","OpportunityHistory","OpportunityLineItem","OpportunityPartner","OpportunityShare","OpportunityStage","Oracle_Vendor_Master__History","OrgLifecycleNotification","OrgWideEmailAddress","Organization","OutOfOffice","OutgoingEmail","OutgoingEmailRelation","Output_Config_Item__History","Output_Config__History","OwnedContentDocument","OwnerChangeOptionInfo","PackageLicense","Partner","PartnerRole","Period","PermissionSet","PermissionSetAssignment","PermissionSetLicense","PermissionSetLicenseAssign","PicklistValueInfo","PlatformAction","PlatformCachePartition","PlatformCachePartitionType","Pricebook2","Pricebook2History","PricebookEntry","ProcessDefinition","ProcessInstance","ProcessInstanceHistory","ProcessInstanceNode","ProcessInstanceStep","ProcessInstanceWorkitem","ProcessNode","Product2","Product2Feed","Product2History","ProductConsumed","ProductConsumedFeed","ProductConsumedHistory","ProductItem","ProductItemFeed","ProductItemHistory","ProductItemShare","ProductItemTransaction","ProductItemTransactionFeed","ProductItemTransactionHistory","ProductRequest","ProductRequestFeed","ProductRequestHistory","ProductRequestLineItem","ProductRequestLineItemFeed","ProductRequestLineItemHistory","ProductRequestShare","ProductRequired","ProductRequiredFeed","ProductRequiredHistory","ProductTransfer","ProductTransferFeed","ProductTransferHistory","ProductTransferShare","Profile","Project2__History","Project_Team_Member__History","Provider__History","Publisher","PushTopic","QueueSobject","QuickText","QuickTextHistory","QuickTextShare","QuoteTemplateRichTextData","RecentlyViewed","RecordAction","RecordActionHistory","RecordType","RelationshipDomain","RelationshipInfo","Report","ReportFeed","ResourceAbsence","ResourceAbsenceFeed","ResourceAbsenceHistory","ResourcePreference","ResourcePreferenceFeed","ResourcePreferenceHistory","ReturnOrder","ReturnOrderFeed","ReturnOrderHistory","ReturnOrderLineItem","ReturnOrderLineItemFeed","ReturnOrderLineItemHistory","ReturnOrderShare","SamlSsoConfig","ScanTech_MRT__History","Scontrol","SearchActivity","SearchLayout","SecureAgentsCluster","SecurityCustomBaseline","ServiceAppointment","ServiceAppointmentFeed","ServiceAppointmentHistory","ServiceAppointmentShare","ServiceAppointmentStatus","ServiceCrew","ServiceCrewFeed","ServiceCrewHistory","ServiceCrewMember","ServiceCrewMemberFeed","ServiceCrewMemberHistory","ServiceCrewShare","ServiceProvider","ServiceReport","ServiceReportHistory","ServiceReportLayout","ServiceResource","ServiceResourceCapacity","ServiceResourceCapacityFeed","ServiceResourceCapacityHistory","ServiceResourceFeed","ServiceResourceHistory","ServiceResourceShare","ServiceResourceSkill","ServiceResourceSkillFeed","ServiceResourceSkillHistory","ServiceTerritory","ServiceTerritoryFeed","ServiceTerritoryHistory","ServiceTerritoryLocation","ServiceTerritoryLocationFeed","ServiceTerritoryLocationHistory","ServiceTerritoryMember","ServiceTerritoryMemberFeed","ServiceTerritoryMemberHistory","ServiceTerritoryShare","SessionPermSetActivation","SetupAuditTrail","SetupEntityAccess","Shipment","ShipmentFeed","ShipmentHistory","ShipmentShare","SignupRequest","SignupRequestFeed","SignupRequestHistory","SignupRequestShare","Site","SiteFeed","SiteHistory","SiteIframeWhiteListUrl","Skill","SkillRequirement","SkillRequirementFeed","SkillRequirementHistory","SocialPersona","SocialPersonaHistory","SocialPost","SocialPostFeed","SocialPostHistory","SocialPostShare","Solution","SolutionFeed","SolutionHistory","SolutionStatus","SsoUserMapping","Stamp","StampAssignment","StaticResource","StreamingChannel","StreamingChannelShare","TabDefinition","Tableau_Project__History","Tableau_Status_By_Provider__History","Task","TaskFeed","TaskPriority","TaskRecurrenceException","TaskRelation","TaskStatus","TaskWhoRelation","TenantSecret","TenantUsageEntitlement","TestSuiteMembership","ThirdPartyAccountLink","TimeSheet","TimeSheetEntry","TimeSheetEntryFeed","TimeSheetEntryHistory","TimeSheetFeed","TimeSheetHistory","TimeSheetShare","TimeSlot","TodayGoal","TodayGoalShare","Topic","TopicAssignment","TopicFeed","TopicUserEvent","TransactionSecurityPolicy","UndecidedEventRelation","User","UserAppInfo","UserAppMenuCustomization","UserAppMenuCustomizationShare","UserAppMenuItem","UserEmailPreferredPerson","UserEmailPreferredPersonShare","UserEntityAccess","UserFeed","UserFieldAccess","UserLicense","UserListView","UserListViewCriterion","UserLogin","UserPackageLicense","UserPermissionAccess","UserPreference","UserProvAccount","UserProvAccountStaging","UserProvMockTarget","UserProvisioningConfig","UserProvisioningLog","UserProvisioningRequest","UserProvisioningRequestShare","UserRecordAccess","UserRole","UserShare","User_History_Tracking__History","VerificationHistory","VisibilityChangeNotification","VisualforceAccessMetrics","Vote","WaveAutoInstallRequest","WaveCompatibilityCheckItem","WebLink","WorkOrder","WorkOrderFeed","WorkOrderHistory","WorkOrderLineItem","WorkOrderLineItemFeed","WorkOrderLineItemHistory","WorkOrderLineItemStatus","WorkOrderShare","WorkOrderStatus","WorkType","WorkTypeFeed","WorkTypeHistory","WorkTypeShare","mc_Chart_DxCode__History","mc_Chart__History","mc_Member__Share","pi__EngageCampaignRecipient__Share","pi__LDFilter__Share","purecloud__PureCloud_Contact_List_Request__History","purecloud__PureCloud_Routing_Request__History"]}
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
	at Function.Buffer.from (buffer.js:202:9)
	at new Buffer (buffer.js:158:17)
	at /Users/dougthompson/Documents/Dev/ForceCode/node_modules/jsforce/lib/api/metadata.js:773:27
	at /Users/dougthompson/Documents/Dev/ForceCode/node_modules/jsforce/lib/promise.js:72:9
	at _combinedTickCallback (internal/process/next_tick.js:131:7)
	at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by doug-episource** [comment]
Debugged deeper and it is related to the "LIMIT_EXCEEDED:Too many files in retrive call, limit is:10000" error. I need to check the Org, we were good before.

It would be great to bubble that error up, though.

**Comment by daishi4u** [comment]
What probably did it was the fact that a few releases ago I added in the ability to download reports, documents, dashboards, and one other foldered type, so I guarantee that's what changed. To get around this, select the types you want to retrieve manually and then you can exclude anything you don't need. Or, if you want everything then do two separate retrieves
