### ISSUE TITLE
"Retrieve Package/Metadata" commands result in "Metadata describe error"

### ISSUE THREAD

**Issue by steinwinde** [celador/ForceCode#315]
Since 2019-09-09 morning retrieve commands like "Retrieve types...", "Get All Files from org", "Get All Apex Classes from org" all fail on all Sandboxes: Instead of any updates, a small VSCode alert box appears at the bottom of the window: "Metadata describe error. Please try logging out of and back into the org." - "Source: ForceCode (Extension)". Logging out and back in doesn't help. The error even occurs in a newly created project after successful authentication. (The download of standard and custom objects somehow works.)

It's probably related to the fact this morning Salesforce installed 47.0 on Sandboxes, but not yet on production and DE orgs.

I've found this error in the Developer Tools console:

Error: EPERM: operation not permitted, rename 'c:\Users\felix\[project directory]\.sfdx' -> 'c:\Users\felix\[project directory]\.forceCode\[Salesforce user name]\.sfdx'
	at Object.renameSync (fs.js:591:3)
	at u (c:\Users\felix\.vscode\extensions\johnaaronnelson.forcecode-3.18.4\dist\src\extension.js:458:283717)
	at c:\Users\felix\.vscode\extensions\johnaaronnelson.forcecode-3.18.4\dist\src\extension.js:458:284056
	at Object.module.exports.e.exports [as moveSync] (c:\Users\felix\.vscode\extensions\johnaaronnelson.forcecode-3.18.4\dist\src\extension.js:458:284140)
	at Object.module.exports.t.default [as configuration] (c:\Users\felix\.vscode\extensions\johnaaronnelson.forcecode-3.18.4\dist\src\extension.js:10:95467)
	at module.exports.t.activate.e.subscriptions.push.n.workspace.createFileSystemWatcher.onDidChange.e (c:\Users\felix\.vscode\extensions\johnaaronnelson.forcecode-3.18.4\dist\src\extension.js:376:91099)
	[...]

ForceCode 3.18.4
VSCode 1.38.0
Node.js 10.11.0
Windows 10
sfdx 7.23.1

**Comment by daishi4u** [comment]
Install 3.18.5 and see if this fixes your issue and let me know

**Comment by PedroPTavaresJr** [comment]
@daishi4u i've just tried it out.
the "retrieve all files from org" is not working on newly created orgs.
if we use it do retrieve/refresh already existing one, it works normally.

works normally in version 3.18.3 (i've installed the older versions to test it out - **3.18.4**, and **3.18.3**)

**Comment by daishi4u** [comment]
3.18.6 fixes this issue
