### ISSUE TITLE
can't delete apex class from org using forcecode UI

### ISSUE THREAD

**Issue by PedroPTavaresJr** [celador/ForceCode#393]
**Describe the bug**
when right clicking on a apex class it gives us the option to delete that class, but for some reason it seems not to be working.

**To Reproduce**
1. Create a class using ForceCode menu (or retrive it from org)
2. Run "ForceCode:Save/Deploy/Compile"
3. Confirm the class creatin on the sandbox
4. Run "ForceCode:Delete file from org"

**Expected behavior**
Class is deleted from org and project folder

**Screenshots**
![image](https://user-images.githubusercontent.com/42211176/108352078-1f25d080-71c5-11eb-8256-cc184e716e53.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version: 1.53
 - ForceCode Version: 3.22.9

**Additional context**
Content of output
---
about to run ForceCode.deleteFile

{
}

{
	status: 1,
	name: TypeError,
	message: Cannot read property 'getElementsByMetadataFilePath' of undefined,
	exitCode: 1,
	commandName: SourceDeleteCommand,
	stack: TypeError: Cannot read property 'getElementsByMetadataFilePath' of undefined
    at C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\lib\source\aggregateSourceElement.js:241:57
    at Array.forEach (<anonymous>)
    at AggregateSourceElement.markForDelete (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\lib\source\aggregateSourceElement.js:234:18)
    at C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\lib\source\sourceDeployApi.js:182:25
    at Array.some (<anonymous>)
    at C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\lib\source\sourceDeployApi.js:177:40
    at Array.forEach (<anonymous>)
    at SourceDeployApi._handleDelete (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\lib\source\sourceDeployApi.js:176:37)
    at SourceDeployApi.doDeploy (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\lib\source\sourceDeployApi.js:82:54)
    at async SourceDeleteCommand.execLegacyCommand (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\ToolbeltCommand.js:149:29)
    at async SourceDeleteCommand.run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\commands\force\source\delete.js:27:16)
    at async SourceDeleteCommand._run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@salesforce\command\lib\sfdxCommand.js:81:40)
    at async Config.runCommand (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@oclif\command\lib\command.js:43:20)
    at async Object.run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\dist\cli.js:32:20)
Outer stack:
    at Function.wrap (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@salesforce\core\lib\sfdxError.js:171:27)
    at SourceDeleteCommand.catch (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\salesforce-alm\dist\ToolbeltCommand.js:248:46)
    at async SourceDeleteCommand._run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@salesforce\command\lib\sfdxCommand.js:85:13)
    at async Config.runCommand (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\node_modules\@oclif\command\lib\command.js:43:20)
    at async Object.run (C:\Users\pedro.tavares\AppData\Local\sfdx\client\7.85.1-2fb9e41053\dist\cli.js:32:20),
	warnings: 
	{
	},
}
Checking login status: Cannot read property 'getElementsByMetadataFilePath' of undefined
Orgs refreshed
Logged in: true
Error reason: undefined
Cannot read property 'getElementsByMetadataFilePath' of undefined

**Comment by daishi4u** [comment]
This seems to be an issue with the sfdx cli. Make sure you're on the newest version by running sfdx update and try again. If it still persists after that, let me know and I'll do more testing.

**Comment by PedroPTavaresJr** [comment]
@daishi4u Thanks for your reply.

just updated the sfdx cli and the problem persists.
everything is at the latest version.
SF extension pack (and all its itens)
forcecode
sfdx cli
visual studio.

i'll add the new log as an attached file, to keep the message clean.
[Log_2021-03-07.txt](https://github.com/celador/ForceCode/files/6097210/Log_2021-03-07.txt)
