### ISSUE TITLE
Getting Windows Error with ForceCode

### ISSUE THREAD

**Issue by mgarf** [celador/ForceCode#5]
Here is the error stack:  Error: %1 is not a valid Win32 application.
\\?\C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.ForceCode-0.1.6\node_modules\xkeychain\build\Release\windows.node
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:158:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) (ELECTRON_ASAR.js:158:20)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.n._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:29921)
    at Module.require (module.js:367:17)

**Comment by mgarf** [comment]
It looks like xkeychain is the issue. Firing on the following line:

var binding = require('../build/Release/windows.node'); on window.js

I went to the node package to log an issue but they seem to have issues disabled. Potentially we need to find an alternative solution for windows?

**Comment by w0ndersp00n** [comment]
This extension is build for Mac. I don't believe this one will ever be compatible with Windows, the developer isn't very communcative regarding this.

**Comment by celador** [comment]
Sorry all.  I will try to keep better track of these issues.  Currently the app is built for Mac only, but I plan to switch out the keychain tool to a cross-platform one soon.  I will keep you posted.

**Comment by mgarf** [comment]
@celador thank you. I saw you already started the commits towards that. I will try to contribute when my workload clears up.

**Comment by mgarf** [comment]
Fixed
