### ISSUE TITLE
svc.newContainer not a function

### ISSUE THREAD

**Issue by mgarf** [celador/ForceCode#90]
Currently trying to compile a class and getting svc.newContainer not a function

Here is the error in the debug log:
```
Invalid URI "/services/data/v37.0/tooling/sobjects/MetadataContainer": Error: Invalid URI "/services/data/v37.0/tooling/sobjects/MetadataContainer"
    at Request.init (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\request\request.js:274:31)
    at new Request (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\request\request.js:128:8)
    at request (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\request\index.js:54:10)
    at C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\request\index.js:101:12
    at createRequest (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\jsforce\lib\transport.js:84:13)
    at Promise.promise.then (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\jsforce\lib\transport.js:43:5)
    at HttpApi.request (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\jsforce\lib\http-api.js:82:47)
    at module.exports.Connection.request (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\jsforce\lib\connection.js:318:18)
    at Tooling.request (C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\jsforce\lib\api\tooling.js:83:29)
    at C:\Users\michael.garfinkel\.vscode\extensions\JohnAaronNelson.forcecode-0.5.13\node_modules\jsforce\lib\connection.js:633:19
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
```

**Comment by mgarf** [comment]
nevermind this is because my login credentials aren't working correctly.
